<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_Login extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_login()
    {
      
    }
}
